// <auto-generated />
using System;
using ClassLibrary584;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassLibrary584.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20211118040102_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClassLibary584.EasternNovelLibary", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<int>("NovelId")
                    .HasColumnType("int");

                b.Property<decimal>("Lat")
                    .HasColumnType("decimal(7,4)");

                b.Property<decimal>("Lon")
                    .HasColumnType("decimal(7,4)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("NovelId");

                b.ToTable("Cities", (string)null);
            });

            modelBuilder.Entity("ClassLibary584NovelLibary", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("ISO2")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ISO3")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("NovelLibary", (string)null);
            });

            modelBuilder.Entity("ClassLibary584.EasternNovelLibary", b =>
            {
                b.HasOne("WorldCitiesAPI.Data.Models.NovelLibary", "NovelLibary")
                    .WithMany("Cities")
                    .HasForeignKey("NovelId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("NovelLibary");
            });

            modelBuilder.Entity("ClassLibary584.NovelLibary", b =>
            {
                b.Navigation("EasternNovelLibary");
            });
#pragma warning restore 612, 618
        }
    }
}